# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c947077dd9eebf5eaa95ce572d9e4637d30507fe5cff8723b2f13f04c3fc7e5fcaddc0719257a3453dee1bb19d7a06f009e578a084c79b0190dd21629a873bde

test:
  secret_key_base: ba5a3b78010628cf5f7c0bdcc7367da68024acb7022259ee4f86f9c86255f4a29b5edc6d4f76a5da1d2ea68d43529f4c5b53a5a1e6eaec26de0781498e3e870c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
